// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class CompetencesLevels
    {
        public CompetencesLevels()
        {
            ProcessCompetences = new HashSet<ProcessCompetences>();
        }

        public int Id { get; set; }
        public string Nazwa { get; set; }

        public virtual ICollection<ProcessCompetences> ProcessCompetences { get; set; }
    }
}
