// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace YouKpiBackend.ModelsEntity
{
    public partial class CompanyBasicInfo
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string FormaPrawna { get; set; }
        public string KodPocztowy { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string Numer { get; set; }
        public string Nip { get; set; }
    }
}