// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class CzesciRysunkiInfo
    {
        public int Id { get; set; }
        public DateTime DataDodania { get; set; }
        public int DodanoPrzezId { get; set; }
        public string Nazwa { get; set; }

        public string CzescId { get; set; }
        public virtual Czesci Czesc { get; set; }

        public int? CzesciRysunkiId { get; set; }
        public virtual CzesciRysunki CzesciRysunki { get; set; }
    }
}