// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Lokacja
    {
        public Lokacja()
        {
            MagazynCzesci = new HashSet<MagazynCzesci>();
            MagazynKomponenty = new HashSet<MagazynKomponenty>();
            MagazynProdukty = new HashSet<MagazynProdukty>();
            MagazynTowary = new HashSet<MagazynTowary>();
        }

        public int Id { get; set; }
        public string Nazwa { get; set; }

        public virtual ICollection<MagazynCzesci> MagazynCzesci { get; set; }
        public virtual ICollection<MagazynKomponenty> MagazynKomponenty { get; set; }
        public virtual ICollection<MagazynProdukty> MagazynProdukty { get; set; }
        public virtual ICollection<MagazynTowary> MagazynTowary { get; set; }
    }
}