// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Maszyny
    {
        public Maszyny()
        {
            PracownikCzasStep = new HashSet<PracownikCzasStep>();
            StepsMachines = new HashSet<StepsMachines>();
        }

        public string Id { get; set; }
        public string Nazwa { get; set; }
        public string Rodzaj { get; set; }
        public string Opis { get; set; }
        public string TrybPracy { get; set; }
        public decimal? OsX { get; set; }
        public decimal? OsY { get; set; }
        public decimal? OsZ { get; set; }
        public string MiejscePracy { get; set; }
        public string Krytycznosc { get; set; }
        public string Status { get; set; }
        public DateTime? DataUruchomienia { get; set; }

        public virtual ICollection<PracownikCzasStep> PracownikCzasStep { get; set; }
        public virtual ICollection<StepsMachines> StepsMachines { get; set; }
    }
}