// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class OfertaTyp
    {
        public int Id { get; set; }
        public string OfferId { get; set; }
        public string Type { get; set; }
    }
}