// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class OfertyView
    {
        public string Idoferty { get; set; }
        public string IdentyfikatorProcesu { get; set; }
        public int NumerKroku { get; set; }
        public string NazwaKroku { get; set; }
        public string IdentyfikatorProjektu { get; set; }
        public string Status { get; set; }
        public string Zamowienie { get; set; }
        public string TypZlecienia { get; set; }
        public DateTime? DataOferty { get; set; }
        public DateTime? DataZapytania { get; set; }
        public string NazwaKlienta { get; set; }
        public string Nip { get; set; }
        public string Ofertujacy { get; set; }
        public DateTime? DataZamowienia { get; set; }
        public DateTime? PlanowanaDataKoncowa { get; set; }
        public string Idwyrobu { get; set; }
        public string TypWyrobu { get; set; }
        public string TypKonstrukcji { get; set; }
        public string TypPrzelotu { get; set; }
        public int? Dn { get; set; }
        public int? Pn { get; set; }
        public string Expr1 { get; set; }
        public int? Quantity { get; set; }
        public string W { get; set; }
        public string Medium { get; set; }
        public string TempMin { get; set; }
        public string TempMax { get; set; }
        public string Uszczelnienie { get; set; }
        public string AdditionalEquipment { get; set; }
        public string PricePerPiece { get; set; }
        public string Currency { get; set; }
        public string Sale { get; set; }
        public double? Wartsoc { get; set; }
        public double? CenaPoRabacie { get; set; }
    }
}