// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Offer
    {
        public Offer()
        {
            OfertaTyp = new HashSet<OfertaTyp>();
            OfferLines = new HashSet<OfferLines>();
            OfferProcess = new HashSet<OfferProcess>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string ProjectsId { get; set; }
        public string Status { get; set; }
        public string OrderType { get; set; }
        public DateTime? OfferDate { get; set; }
        public int ClientsId { get; set; }
        public int? Offerrer { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? PlannedEnd { get; set; }

        public virtual Client Clients { get; set; }
        public virtual Pracownik OfferrerNavigation { get; set; }
        public virtual ICollection<OfertaTyp> OfertaTyp { get; set; }
        public virtual ICollection<OfferLines> OfferLines { get; set; }
        public virtual ICollection<OfferProcess> OfferProcess { get; set; }
    }
}