// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Offer
    {
        public string Id { get; set; }
        public string ProjectsId { get; set; }
        public string Status { get; set; }
        public string OrderType { get; set; }
        public DateTime? OfferDate { get; set; }
        public string ClientsId { get; set; }
        public string Offerrer { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? PlannedEnd { get; set; }
    }
}