// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class OfferOfferLinesConnection
    {
        public int OfferLineId { get; set; }
        public int? OfferId { get; set; }

        public virtual Offer Offer { get; set; }
        public virtual OfferLines OfferLine { get; set; }
    }
}