// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class OrderRealisation
    {
        public string OrderId { get; set; }
        public int? PozycjaZamowienia { get; set; }
        public string KlientId { get; set; }
        public string ProcessId { get; set; }
        public int? IdProcessStep { get; set; }
        public string Status { get; set; }
        public int? DifferenceReasonCodeId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? PlanowanaDataKoncowa { get; set; }
        public DateTime? ZakonczenieData { get; set; }
        public int? Wynik { get; set; }
        public string TypZlecenia { get; set; }
        public int? SekwencjaProcesuDays { get; set; }
        public string WyrobId { get; set; }
        public string TypWyrobu { get; set; }
        public string NazwaCzesci { get; set; }
        public int? Dn { get; set; }
        public int? Pn { get; set; }
        public int? Ps { get; set; }
        public int? IloscWyrobow { get; set; }
        public string Wersja { get; set; }
        public int? NumerZaworu { get; set; }
        public int? NajwyzszyNrFabryczny { get; set; }
        public int? IloscPomiarow { get; set; }
        public int? PomiarowNok { get; set; }
        public string FypIn { get; set; }
        public string FypOut { get; set; }
        public string NumerSj { get; set; }
        public DateTime? CzasWytworzeniaTpz { get; set; }
        public DateTime? CzasWytworzeniaTj { get; set; }
        public string Cpo { get; set; }
        public int? PracownikId { get; set; }
        public string ImieNazwisko { get; set; }
        public string NumerZzu { get; set; }
        public DateTime? StartMaszyna { get; set; }
        public DateTime? StopMaszyna { get; set; }
        public DateTime? CzasPracyOgolemMaszyna { get; set; }
        public string MaszynaId { get; set; }
    }
}