// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Pracownik
    {
        public Pracownik()
        {
            Offer = new HashSet<Offer>();
            PracownikProcess = new HashSet<PracownikProcess>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int TrybPracy { get; set; }
        public int CzasDostepuMin { get; set; }
        public bool IsAdministrator { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Salt { get; set; }

        public virtual ICollection<Offer> Offer { get; set; }
        public virtual ICollection<PracownikProcess> PracownikProcess { get; set; }
    }
}