// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class PracownikCzasStep
    {
        public int Id { get; set; }
        public int OfferLinesId { get; set; }
        public int ProcessStepsId { get; set; }
        public int PracownikId { get; set; }
        public int LiczbaMinut { get; set; }
    }
}