// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class PracownikProcess
    {
        public int Id { get; set; }
        public int PracownikId { get; set; }
        public string ProcessId { get; set; }

        public virtual Pracownik Pracownik { get; set; }
    }
}