// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
<<<<<<< HEAD:YouKpiBackend/ModelsEntity/PracownikCzasStep.cs
    public partial class PracownikCzasStep
    {
        public int Id { get; set; }
        public int OfferLinesId { get; set; }
        public int ProcessStepsId { get; set; }
        public int PracownikId { get; set; }
        public int LiczbaMinut { get; set; }
=======
    public partial class OfferProcess
    {
        public int Id { get; set; }
        public int OfferId { get; set; }
        public string ProcessId { get; set; }

        public virtual Offer Offer { get; set; }
        public virtual Process Process { get; set; }
>>>>>>> d4ad46cc4ea85339f5ffaa37665c09864dfe7a17:YouKpiBackend/ModelsEntity/OfferProcess.cs
    }
}