// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Process
    {
        public Process()
        {
            OfferLineProcess = new HashSet<OfferLineProcess>();
            OfferProcess = new HashSet<OfferProcess>();
            PracownikCzasStep = new HashSet<PracownikCzasStep>();
            ProcessesProcessProcess = new HashSet<ProcessesProcess>();
            ProcessesProcessRelatedProcess = new HashSet<ProcessesProcess>();
            Steps = new HashSet<Steps>();
            ProcessCompetences = new HashSet<ProcessCompetences>();
            ProcessSubjects = new HashSet<ProcessesProcessSubjects>();
            ProcessAreas = new HashSet<ProcessesProcessAreas>();
        }

        public string Id { get; set; }
        public string NazwaGrupyProcesu { get; set; }
        public string BusinessArea { get; set; }
        public string NazwaProcesu { get; set; }
        public string KontoGłówne { get; set; }
        public string TypZlecenia { get; set; }

        public virtual ICollection<ProcessesProcessSubjects> ProcessSubjects { get; set; }
        public virtual ICollection<ProcessesProcessAreas> ProcessAreas { get; set; }
        public virtual ICollection<OfferLineProcess> OfferLineProcess { get; set; }
        public virtual ICollection<OfferProcess> OfferProcess { get; set; }
        public virtual ICollection<PracownikCzasStep> PracownikCzasStep { get; set; }
        public virtual ICollection<ProcessesProcess> ProcessesProcessProcess { get; set; }
        public virtual ICollection<ProcessesProcess> ProcessesProcessRelatedProcess { get; set; }
        public virtual ICollection<Steps> Steps { get; set; }
        public virtual ICollection<ProcessCompetences> ProcessCompetences { get; set; }
    }
}