// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Processes
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public int? SeqWeek { get; set; }
        public int? SeqDays { get; set; }
        public int? SeqHrs { get; set; }
        public string Bpregion { get; set; }
        public string BpprocessParent { get; set; }
        public string BpprocessSub { get; set; }
        public string SpiceDescription { get; set; }
        public string Bpprocess { get; set; }
        public string Bppep { get; set; }
        public string BpproductProcess { get; set; }
        public string BpkapaBench { get; set; }
        public string BpmainAccount { get; set; }
        public string Bpbenchmark1 { get; set; }
        public string Bpbenchmark2 { get; set; }
        public string Bpbenchmark3 { get; set; }
        public string BpbenchProcessQual { get; set; }
        public string BpbenchQualNorm { get; set; }
        public string BpbenchQualSoft { get; set; }
    }
}