// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Process
    {
        public string Id { get; set; }
        public string NazwaGrupyProcesu { get; set; }
        public string BusinessArea { get; set; }
        public string NazwaProcesu { get; set; }
        public string KontoGłówne { get; set; }
        public string TypZlecenia { get; set; }
    }
}