// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class ProcessCompetences
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public int Wartosc { get; set; }
        public int Cel { get; set; }
        public int? CompetenceLevelId { get; set; }
        public virtual CompetencesLevels CompetenceLevel { get; set; }
        public int OkresOceny { get; set; }
        public string Typ { get; set; }

        public string ProcessId { get; set; }
        public virtual Process Processes { get; set; }
    }
}
