// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Produkty
    {
        public Produkty()
        {
            ProduktCzesci = new HashSet<ProduktCzesci>();
        }

        public string Id { get; set; }
        public string TypWyrobuId { get; set; }
        public string NumerRysNorma { get; set; }
        public int Dn { get; set; }
        public int Pn { get; set; }
        public string Ansi { get; set; }
        public string Wersja { get; set; }
        public string Uszczelnienie { get; set; }

        public virtual ICollection<ProduktCzesci> ProduktCzesci { get; set; }
    }
}