// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class ProduktyRysunkiInfo
    {
        public int Id { get; set; }
        public DateTime DataDodania { get; set; }
        public int DodanoPrzezId { get; set; }
        public string Nazwa { get; set; }

        public int? ProduktId { get; set; }
        public virtual Produkty Produkt { get; set; }

        public int? ProduktyRysunkiId { get; set; }
        public virtual ProduktyRysunki ProduktyRysunki { get; set; }
    }
}