// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace YouKpiBackend.ModelsEntity
{
    public partial class ProduktyOld
    {
        public string Id { get; set; }
        public string TypWyrobuId { get; set; }
        public string NumerRysNorma { get; set; }
        public int Dn { get; set; }
        public int Pn { get; set; }
        public string Ansi { get; set; }
        public string Wersja { get; set; }
        public string Uszczelnienie { get; set; }
        public int WymiaryDlmm { get; set; }
        public int WymianyRmm { get; set; }
        public int WymiarHmm { get; set; }
        public int Kvs { get; set; }
        public decimal Waga { get; set; }
        public string WagaJednostka { get; set; }
    }
}