// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace YouKpiBackend.ModelsEntity
{
    public partial class Projects
    {
        public string Id { get; set; }
        public string Description { get; set; }
        public string ProductNrClient { get; set; }
        public string ProductNrInt { get; set; }
        public string QafNr { get; set; }
        public string To { get; set; }
        public string Status { get; set; }
        public string Phase { get; set; }
        public string DateOfferd { get; set; }
        public string DateTd { get; set; }
        public string Nomination { get; set; }
        public string RodzajProjektu { get; set; }
        public string Location { get; set; }
        public string Version { get; set; }
        public string Client { get; set; }
        public string ClientGroup { get; set; }
        public string ProductType { get; set; }
        public string ProductSubType { get; set; }
        public string FunelStep { get; set; }
        public string Funel { get; set; }
    }
}