// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class ReasonCodes
    {
        public int Id { get; set; }
        public int? IdDifferenceReasonCode { get; set; }
        public string Opis { get; set; }
    }
}