// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class StepOfferWykonanie
    {
        public int Id { get; set; }
        public int OfferLineId { get; set; }
        public string ProcessId { get; set; }
        public int LiczbaPomiarow { get; set; }
        public int LiczbaPomiarowNok { get; set; }
        public bool Zakonczonie { get; set; }
        public int Step { get; set; }
    }
}