// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class StepsMachines
    {
        public int Id { get; set; }
        public int StepId { get; set; }
        public int MaszynyId { get; set; }
    }
}