// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Steps
    {
        public Steps()
        {
            StepsMachines = new HashSet<StepsMachines>();
        }

        public int Id { get; set; }
        public string StepId { get; set; }
        public string StepName { get; set; }
        public int StepNum { get; set; }
        public string ProcessesId { get; set; }
        public int Sekwencja { get; set; }

        public virtual Process Processes { get; set; }
        public virtual ICollection<StepsMachines> StepsMachines { get; set; }
    }
}