// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class StepsMachines
    {
        public int Id { get; set; }
        public int? StepId { get; set; }
        public string MachineId { get; set; }

        public virtual Maszyny Machine { get; set; }
        public virtual Steps Step { get; set; }
    }
}