// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace YouKpiBackend.ModelsEntity
{
    public partial class StepsToDelete
    {
        public int Id { get; set; }
        public string StepName { get; set; }
        public int StepNum { get; set; }
        public string ProcessesId { get; set; }
        public int Sekwencja { get; set; }
    }
}