// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Steps
    {
        public int Id { get; set; }
        public string StepName { get; set; }
        public string StepNum { get; set; }
        public string ProcessesId { get; set; }
    }
}