// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Towary
    {
        public Towary()
        {
            MagazynTowary = new HashSet<MagazynTowary>();
        }

        public string Id { get; set; }
        public string Nazwa { get; set; }
        public int? ClientId { get; set; }
        public string WalutaZakupu { get; set; }
        public string WalutaSprzedazy { get; set; }
        public decimal? CenaSprzedazy { get; set; }
        public decimal? CenaZakupu { get; set; }

        public virtual ICollection<MagazynTowary> MagazynTowary { get; set; }
    }
}