// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class Towary
    {
        public string Id { get; set; }
        public string Nazwa { get; set; }
    }
}