// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace YouKpiBackend.ModelsEntity
{
    public partial class TypWyrobu
    {
        public string Id { get; set; }
        public string IdgrupyWyrobu { get; set; }
        public string TypKonstrukcji { get; set; }
        public string TypPrzelotu { get; set; }
        public string TypKuli { get; set; }
    }
}