// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YouKpiBackend.ModelsEntity
{
    public partial class TypWyrobuIdDn
    {
        public string TypWyrobuId { get; set; }
        public int WymiaryDlmm { get; set; }
        public int WymianyRmm { get; set; }
        public int WymiarHmm { get; set; }
        public int Kvs { get; set; }
        public decimal Waga { get; set; }
        public string WagaJednostka { get; set; }
        public int? Dn { get; set; }
        public int TempMin { get; set; }
        public int TempMax { get; set; }
    }
}