// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace YouKpiBackend.ModelsEntity
{
    [NotMapped]
    public partial class VOtifReport
    {
        public DateTime? PlannedEndOffer { get; set; }
        public string ProcessId { get; set; }
        public string NazwaProcesu { get; set; }
        public int StepNum { get; set; }
        public int Sekwencja { get; set; }
        public DateTime? ClosedOn { get; set; }
        public string NazwaGrupyProcesu { get; set; }
        public int? StepShouldEndBeforeDays { get; set; }
    }
}