// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Data;
using System.Threading.Tasks;
using YouKpiBackend.ModelsEntity;

namespace YouKpiBackend.DbContexts
{
    public partial class YoukpiContextProcedures
    {
        private readonly YoukpiContext _context;

        public YoukpiContextProcedures(YoukpiContext context)
        {
            _context = context;
        }

        public async Task<int> OfferAll(OutputParameter<int> returnValue = null)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[OfferAll]", parameterreturnValue);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
