// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using YouKpiBackend.ModelsEntity;

namespace YouKpiBackend.DbContexts
{
    public partial class YoukpiContext : DbContext
    {
        public YoukpiContext()
        {
        }

        public YoukpiContext(DbContextOptions<YoukpiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Czesci> Czesci { get; set; }
        public virtual DbSet<OfertyView> OfertyView { get; set; }
        public virtual DbSet<Offer> Offer { get; set; }
        public virtual DbSet<OfferLines> OfferLines { get; set; }
        public virtual DbSet<Processes> Processes { get; set; }
        public virtual DbSet<ProduktCzesci> ProduktCzesci { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<ProduktyOld> ProduktyOld { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Steps> Steps { get; set; }
        public virtual DbSet<TypWyrobu> TypWyrobu { get; set; }
        public virtual DbSet<TypWyrobuIdDn> TypWyrobuIdDn { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Client>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Nip)
                    .IsRequired()
                    .HasColumnName("NIP")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .IsFixedLength();
            });

            modelBuilder.Entity<Czesci>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.GatPodstawowy)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Nazwa)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.NumerRysNorma)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<OfertyView>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("OfertyView");

                entity.Property(e => e.Currency).HasMaxLength(4);

                entity.Property(e => e.DataOferty).HasColumnType("datetime");

                entity.Property(e => e.DataZamowienia).HasColumnType("datetime");

                entity.Property(e => e.DataZapytania).HasColumnType("datetime");

                entity.Property(e => e.Dn).HasColumnName("DN");

                entity.Property(e => e.Expr1)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.IdentyfikatorProcesu).HasMaxLength(50);

                entity.Property(e => e.IdentyfikatorProjektu).HasMaxLength(50);

                entity.Property(e => e.Idoferty)
                    .IsRequired()
                    .HasColumnName("IDOferty")
                    .HasMaxLength(50);

                entity.Property(e => e.Idwyrobu)
                    .HasColumnName("IDWyrobu")
                    .HasMaxLength(50);

                entity.Property(e => e.Medium).HasMaxLength(150);

                entity.Property(e => e.NazwaKlienta)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.NazwaKroku)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Nip)
                    .HasColumnName("NIP")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Ofertujacy).HasMaxLength(50);

                entity.Property(e => e.PlanowanaDataKoncowa).HasColumnType("datetime");

                entity.Property(e => e.Pn).HasColumnName("PN");

                entity.Property(e => e.PricePerPiece).HasMaxLength(50);

                entity.Property(e => e.Sale).HasMaxLength(50);

                entity.Property(e => e.Status).HasMaxLength(50);

                entity.Property(e => e.TempMax).HasMaxLength(50);

                entity.Property(e => e.TempMin).HasMaxLength(50);

                entity.Property(e => e.TypKonstrukcji)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.TypPrzelotu)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.TypWyrobu)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.TypZlecienia)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Uszczelnienie).HasMaxLength(20);

                entity.Property(e => e.W).HasMaxLength(50);

                entity.Property(e => e.Zamowienie).HasMaxLength(50);
            });

            modelBuilder.Entity<Offer>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .HasMaxLength(50);

                entity.Property(e => e.ClientsId).HasMaxLength(50);

                entity.Property(e => e.OfferDate).HasColumnType("datetime");

                entity.Property(e => e.Offerrer).HasMaxLength(50);

                entity.Property(e => e.Order).HasMaxLength(50);

                entity.Property(e => e.OrderDate).HasColumnType("datetime");

                entity.Property(e => e.OrderType)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.PlannedEnd).HasColumnType("datetime");

                entity.Property(e => e.ProcessesId).HasMaxLength(50);

                entity.Property(e => e.ProjectsId).HasMaxLength(50);

                entity.Property(e => e.QueryDate).HasColumnType("datetime");

                entity.Property(e => e.Status).HasMaxLength(50);
            });

            modelBuilder.Entity<OfferLines>(entity =>
            {
                entity.HasIndex(e => e.Id)
                    .HasName("IX_OfferLines");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Currency).HasMaxLength(4);

                entity.Property(e => e.Medium).HasMaxLength(150);

                entity.Property(e => e.OfferId)
                    .IsRequired()
                    .HasColumnName("OfferID")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PricePerPiece).HasMaxLength(50);

                entity.Property(e => e.ProductId)
                    .HasColumnName("ProductID")
                    .HasMaxLength(50);

                entity.Property(e => e.Sale).HasMaxLength(50);

                entity.Property(e => e.StepId).HasColumnName("StepID");

                entity.Property(e => e.TempMax).HasMaxLength(50);

                entity.Property(e => e.TempMin).HasMaxLength(50);

                entity.Property(e => e.W).HasMaxLength(50);
            });

            modelBuilder.Entity<Processes>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .HasMaxLength(15);

                entity.Property(e => e.BpbenchProcessQual)
                    .HasColumnName("BPBenchProcessQual")
                    .HasMaxLength(200);

                entity.Property(e => e.BpbenchQualNorm)
                    .HasColumnName("BPBenchQualNorm")
                    .HasMaxLength(200);

                entity.Property(e => e.BpbenchQualSoft)
                    .HasColumnName("BPBenchQualSoft")
                    .HasMaxLength(200);

                entity.Property(e => e.Bpbenchmark1)
                    .HasColumnName("BPBenchmark_1")
                    .HasMaxLength(200);

                entity.Property(e => e.Bpbenchmark2)
                    .HasColumnName("BPBenchmark_2")
                    .HasMaxLength(200);

                entity.Property(e => e.Bpbenchmark3)
                    .HasColumnName("BPBenchmark_3")
                    .HasMaxLength(200);

                entity.Property(e => e.BpkapaBench)
                    .HasColumnName("BPKapaBench")
                    .HasMaxLength(200);

                entity.Property(e => e.BpmainAccount)
                    .HasColumnName("BPMainAccount")
                    .HasMaxLength(200);

                entity.Property(e => e.Bppep)
                    .HasColumnName("BPPep")
                    .HasMaxLength(200);

                entity.Property(e => e.Bpprocess)
                    .HasColumnName("BPProcess")
                    .HasMaxLength(200);

                entity.Property(e => e.BpprocessParent)
                    .HasColumnName("BPProcessParent")
                    .HasMaxLength(200);

                entity.Property(e => e.BpprocessSub)
                    .HasColumnName("BPProcessSub")
                    .HasMaxLength(200);

                entity.Property(e => e.BpproductProcess)
                    .HasColumnName("BPProductProcess")
                    .HasMaxLength(200);

                entity.Property(e => e.Bpregion)
                    .HasColumnName("BPRegion")
                    .HasMaxLength(20);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Owner).HasMaxLength(200);

                entity.Property(e => e.SeqDays).HasColumnName("seqDays");

                entity.Property(e => e.SeqHrs).HasColumnName("SeqHRS");

                entity.Property(e => e.SpiceDescription).HasMaxLength(200);
            });

            modelBuilder.Entity<ProduktCzesci>(entity =>
            {
                entity.Property(e => e.CzesciId)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.ProduktyId)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.HasOne(d => d.Czesci)
                    .WithMany(p => p.ProduktCzesci)
                    .HasForeignKey(d => d.CzesciId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("ProduktCzesci_Czesci_FK");

                entity.HasOne(d => d.Produkty)
                    .WithMany(p => p.ProduktCzesci)
                    .HasForeignKey(d => d.ProduktyId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("ProduktCzesci_Produkty_FK");
            });

            modelBuilder.Entity<Produkty>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Ansi)
                    .IsRequired()
                    .HasColumnName("ANSI")
                    .HasMaxLength(5);

                entity.Property(e => e.Dn).HasColumnName("DN");

                entity.Property(e => e.NumerRysNorma)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Pn).HasColumnName("PN");

                entity.Property(e => e.TypWyrobuId)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Uszczelnienie)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Wersja)
                    .IsRequired()
                    .HasMaxLength(5);
            });

            modelBuilder.Entity<ProduktyOld>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("Produkty_old");

                entity.Property(e => e.Ansi)
                    .IsRequired()
                    .HasColumnName("ANSI")
                    .HasMaxLength(5);

                entity.Property(e => e.Dn).HasColumnName("DN");

                entity.Property(e => e.Id)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.NumerRysNorma)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Pn).HasColumnName("PN");

                entity.Property(e => e.TypWyrobuId)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Uszczelnienie)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Waga).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.WagaJednostka)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasDefaultValueSql("(N'kg')");

                entity.Property(e => e.Wersja)
                    .IsRequired()
                    .HasMaxLength(5);

                entity.Property(e => e.WymiaryDlmm).HasColumnName("WymiaryDLmm");
            });

            modelBuilder.Entity<Projects>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Client).HasMaxLength(5);

                entity.Property(e => e.ClientGroup).HasMaxLength(50);

                entity.Property(e => e.DateOfferd).HasMaxLength(50);

                entity.Property(e => e.DateTd)
                    .HasColumnName("DateTD")
                    .HasMaxLength(20);

                entity.Property(e => e.Description).HasMaxLength(255);

                entity.Property(e => e.Funel).HasMaxLength(40);

                entity.Property(e => e.FunelStep).HasMaxLength(255);

                entity.Property(e => e.Id)
                    .IsRequired()
                    .HasColumnName("ID")
                    .HasMaxLength(50);

                entity.Property(e => e.Location).HasMaxLength(10);

                entity.Property(e => e.Nomination).HasMaxLength(8);

                entity.Property(e => e.Phase).HasMaxLength(10);

                entity.Property(e => e.ProductNrClient).HasMaxLength(100);

                entity.Property(e => e.ProductNrInt).HasMaxLength(20);

                entity.Property(e => e.ProductSubType).HasMaxLength(50);

                entity.Property(e => e.ProductType).HasMaxLength(50);

                entity.Property(e => e.QafNr).HasMaxLength(255);

                entity.Property(e => e.RodzajProjektu).HasMaxLength(10);

                entity.Property(e => e.Status).HasMaxLength(20);

                entity.Property(e => e.To).HasMaxLength(25);

                entity.Property(e => e.Version).HasMaxLength(10);
            });

            modelBuilder.Entity<Steps>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.ProcessesId)
                    .IsRequired()
                    .HasColumnName("ProcessesID")
                    .HasMaxLength(50);

                entity.Property(e => e.StepName)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.StepNum)
                    .IsRequired()
                    .HasMaxLength(200);
            });

            modelBuilder.Entity<TypWyrobu>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.IdgrupyWyrobu)
                    .IsRequired()
                    .HasColumnName("IDGrupyWyrobu")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.TypKonstrukcji)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.TypKuli)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('pływajaca')");

                entity.Property(e => e.TypPrzelotu)
                    .HasMaxLength(30)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TypWyrobuIdDn>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Dn).HasColumnName("DN");

                entity.Property(e => e.TypWyrobuId)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Waga).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.WagaJednostka)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.WymiaryDlmm).HasColumnName("WymiaryDLmm");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}