// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using YouKpiBackend.ModelsEntity;

namespace YouKpiBackend.DbContexts
{
    public partial class YoukpiContext : DbContext
    {
        public YoukpiContext()
        {
        }

        public YoukpiContext(DbContextOptions<YoukpiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BusiessArea> BusiessArea { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<MediumsDictionary> MediumsDictionary { get; set; }
        public virtual DbSet<CompetencesLevels> CompetencesLevels { get; set; }
        public virtual DbSet<ProcessCompetences> ProcessCompetences { get; set; }
        public virtual DbSet<CompanyBasicInfo> CompanyBasicInfo { get; set; }
        public virtual DbSet<Czesci> Czesci { get; set; }
        public virtual DbSet<Komponenty> Komponenty { get; set; }
        public virtual DbSet<Kontrahent> Kontrahent { get; set; }
        public virtual DbSet<Lokacja> Lokacja { get; set; }
        public virtual DbSet<MagazynCzesci> MagazynCzesci { get; set; }
        public virtual DbSet<MagazynKomponenty> MagazynKomponenty { get; set; }
        public virtual DbSet<MagazynProdukty> MagazynProdukty { get; set; }
        public virtual DbSet<MagazynProduktyNiezgodne> MagazynProduktyNiezgodne { get; set; }
        public virtual DbSet<MagazynTowary> MagazynTowary { get; set; }
        public virtual DbSet<Maszyny> Maszyny { get; set; }
        public virtual DbSet<MozliweStatusyOferty> MozliweStatusyOferty { get; set; }
        public virtual DbSet<MozliwyDn> MozliwyDn { get; set; }
        public virtual DbSet<MozliwyOrderType> MozliwyOrderType { get; set; }
        public virtual DbSet<MożliwaGrupaProcesu> MożliwaGrupaProcesu { get; set; }
        public virtual DbSet<NlogAllErrors> NlogAllErrors { get; set; }
        public virtual DbSet<NlogAsp> NlogAsp { get; set; }
        public virtual DbSet<NlogOwn> NlogOwn { get; set; }
        public virtual DbSet<Offer> Offer { get; set; }
        public virtual DbSet<OfferLineProcess> OfferLineProcess { get; set; }
        public virtual DbSet<OfferLines> OfferLines { get; set; }
        public virtual DbSet<OfferProcess> OfferProcess { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<PracownikCzasStep> PracownikCzasStep { get; set; }
        public virtual DbSet<PracownikProcess> PracownikProcess { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<ProcessesProcess> ProcessesProcess { get; set; }
        public virtual DbSet<VProdExe> VProdExe { get; set; }
        public virtual DbSet<ProduktCzesci> ProduktCzesci { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<ProduktyRysunki> ProduktyRysunki { get; set; }
        public virtual DbSet<ProduktyRysunkiInfo> ProduktyRysunkiInfo { get; set; }
        public virtual DbSet<CzesciRysunki> CzesciRysunki { get; set; }
        public virtual DbSet<CzesciRysunkiInfo> CzesciRysunkiInfo { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<ReasonCodes> ReasonCodes { get; set; }
        public virtual DbSet<StepOfferWykonanie> StepOfferWykonanie { get; set; }
        public virtual DbSet<Steps> Steps { get; set; }
        public virtual DbSet<StepsMachines> StepsMachines { get; set; }
        public virtual DbSet<Towary> Towary { get; set; }
        public virtual DbSet<TypWyrobu> TypWyrobu { get; set; }
        public virtual DbSet<TypWyrobuIdDn> TypWyrobuIdDn { get; set; }
        public virtual DbSet<VActivityHistory> VActivityHistory { get; set; }
        public virtual DbSet<VOtifReport> VOtifReport { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BusiessArea>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<MediumsDictionary>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                entity.Property(e => e.Name)
                    .HasMaxLength(150)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CompetencesLevels>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                entity.Property(e => e.Nazwa)
                    .HasMaxLength(150)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<ProcessCompetences>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                entity.Property(e => e.Nazwa)
                 .IsUnicode(false);

                entity.Property(e => e.Wartosc)
                 .IsUnicode(false);
                 
                entity.Property(e => e.Cel)
                 .IsUnicode(false);

                entity.Property(e => e.OkresOceny)
                 .IsUnicode(false);

                entity.Property(e => e.Typ)
                .IsUnicode(false);

                entity.HasOne(d => d.Processes)
                  .WithMany(p => p.ProcessCompetences)
                  .HasForeignKey(d => d.ProcessId)
                  .HasConstraintName("FK_PROCESS_PROCESSCOMPETENCE_ID");

                entity.HasOne(d => d.CompetenceLevel)
                    .WithMany(p => p.ProcessCompetences)
                    .HasForeignKey(d => d.CompetenceLevelId)
                    .HasConstraintName("FK_PROCESS_COMPETENCELEVEL_ID");
            });

            modelBuilder.Entity<Client>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Email)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.KodPocztowy)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Miasto)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Nip)
                    .HasColumnName("NIP")
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.NrBudynku)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.NrTelefonu)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.OsobaKontaktowa)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Ulica)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CompanyBasicInfo>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.FormaPrawna).HasMaxLength(2000);

                entity.Property(e => e.KodPocztowy).HasMaxLength(10);

                entity.Property(e => e.Miasto).HasMaxLength(100);

                entity.Property(e => e.Nazwa).HasMaxLength(2000);

                entity.Property(e => e.Nip)
                    .HasColumnName("NIP")
                    .HasMaxLength(20);

                entity.Property(e => e.Numer).HasMaxLength(10);

                entity.Property(e => e.Ulica).HasMaxLength(200);
            });

            modelBuilder.Entity<Czesci>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.GatPodstawowy)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Nazwa)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.NumerProgramu)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.NumerRysNorma)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Tj)
                    .HasColumnName("TJ")
                    .HasColumnType("decimal(6, 2)");

                entity.Property(e => e.Tpz)
                    .HasColumnName("TPZ")
                    .HasColumnType("decimal(6, 2)");

                entity.Property(e => e.Wykonanie)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Wymiary).HasMaxLength(50);

                entity.HasOne(d => d.Komponent)
                    .WithMany(p => p.Czesci)
                    .HasForeignKey(d => d.KomponentId)
                    .HasConstraintName("FK__Czesci__Komponen__79C80F94");
            });

            modelBuilder.Entity<Komponenty>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CenaJednostkowa).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.GatunekPodst)
                    .HasMaxLength(300)
                    .IsUnicode(false);

                entity.Property(e => e.Ilosc).HasColumnType("decimal(11, 6)");

                entity.Property(e => e.Jednostka)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KomponentId)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Ltid).HasColumnName("LTID");

                entity.Property(e => e.Nazwa)
                    .HasMaxLength(300)
                    .IsUnicode(false);

                entity.Property(e => e.ProcessId).HasMaxLength(30);

                entity.Property(e => e.Wymiar)
                    .HasMaxLength(300)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Kontrahent>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Email)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.KodPocztowy)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Miasto)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Nip)
                    .IsRequired()
                    .HasColumnName("NIP")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.NrBudynku)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.NrTelefonu)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.Ulica)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Lokacja>(entity =>
            {
                entity.Property(e => e.Nazwa)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<MagazynCzesci>(entity =>
            {
                entity.Property(e => e.CenaJdnNetto).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.DataPrzyjecia).HasColumnType("datetime");

                entity.Property(e => e.ElementId)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Jednostka)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.NrFakturyId)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.Element)
                    .WithMany(p => p.MagazynCzesci)
                    .HasForeignKey(d => d.ElementId)
                    .HasConstraintName("FK_Czesci");

                entity.HasOne(d => d.Kontrahent)
                    .WithMany(p => p.MagazynCzesci)
                    .HasForeignKey(d => d.KontrahentId)
                    .HasConstraintName("FK_Kontrahent");

                entity.HasOne(d => d.Lokacja)
                    .WithMany(p => p.MagazynCzesci)
                    .HasForeignKey(d => d.LokacjaId)
                    .HasConstraintName("FK_Lokacje");
            });

            modelBuilder.Entity<MagazynKomponenty>(entity =>
            {
                entity.Property(e => e.CenaJdnNetto).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.DataPrzyjecia).HasColumnType("datetime");

                entity.Property(e => e.Jednostka)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.NrFakturyId)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.Element)
                    .WithMany(p => p.MagazynKomponenty)
                    .HasForeignKey(d => d.ElementId)
                    .HasConstraintName("FK_Komponenty");

                entity.HasOne(d => d.Kontrahent)
                    .WithMany(p => p.MagazynKomponenty)
                    .HasForeignKey(d => d.KontrahentId)
                    .HasConstraintName("FK_KontrahentKomponenty");

                entity.HasOne(d => d.Lokacja)
                    .WithMany(p => p.MagazynKomponenty)
                    .HasForeignKey(d => d.LokacjaId)
                    .HasConstraintName("FK_LokacjePKomponenty");
            });

            modelBuilder.Entity<MagazynProdukty>(entity =>
            {
                entity.Property(e => e.CenaJdnNetto).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.DataPrzyjecia).HasColumnType("datetime");

                entity.Property(e => e.Jednostka)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.NrFakturyId)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.Element)
                    .WithMany(p => p.MagazynProdukty)
                    .HasForeignKey(d => d.ElementId)
                    .HasConstraintName("FK_Produkty");

                entity.HasOne(d => d.Kontrahent)
                    .WithMany(p => p.MagazynProdukty)
                    .HasForeignKey(d => d.KontrahentId)
                    .HasConstraintName("FK_KontrahentProdukty");

                entity.HasOne(d => d.Lokacja)
                    .WithMany(p => p.MagazynProdukty)
                    .HasForeignKey(d => d.LokacjaId)
                    .HasConstraintName("FK_LokacjeProdukty");
            });

            modelBuilder.Entity<MagazynProduktyNiezgodne>(entity =>
            {
                entity.Property(e => e.CenaJdnNetto).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.DataPrzyjecia).HasColumnType("datetime");

                entity.Property(e => e.Jednostka)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.NrFakturyId)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.Element)
                    .WithMany(p => p.MagazynProduktyNiezgodne)
                    .HasForeignKey(d => d.ElementId)
                    .HasConstraintName("FK_ProduktyNiezgodne");

                entity.HasOne(d => d.Kontrahent)
                    .WithMany(p => p.MagazynProduktyNiezgodne)
                    .HasForeignKey(d => d.KontrahentId)
                    .HasConstraintName("FK_KontrahentProduktyNiezgodne");

                entity.HasOne(d => d.Lokacja)
                    .WithMany(p => p.MagazynProduktyNiezgodne)
                    .HasForeignKey(d => d.LokacjaId)
                    .HasConstraintName("FK_LokacjeProduktyNiezgodne");
            });

            modelBuilder.Entity<MagazynTowary>(entity =>
            {
                entity.Property(e => e.CenaJdnNetto).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.DataPrzyjecia).HasColumnType("datetime");

                entity.Property(e => e.ElementId)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Jednostka)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Nazwa)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.NrFakturyId)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.Element)
                    .WithMany(p => p.MagazynTowary)
                    .HasForeignKey(d => d.ElementId)
                    .HasConstraintName("FK__MagazynTo__Eleme__23BE4960");

                entity.HasOne(d => d.Kontrahent)
                    .WithMany(p => p.MagazynTowary)
                    .HasForeignKey(d => d.KontrahentId)
                    .HasConstraintName("FK__MagazynTo__Kontr__24B26D99");

                entity.HasOne(d => d.Lokacja)
                    .WithMany(p => p.MagazynTowary)
                    .HasForeignKey(d => d.LokacjaId)
                    .HasConstraintName("FK__MagazynTo__Lokac__25A691D2");
            });

            modelBuilder.Entity<Maszyny>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.DataUruchomienia).HasColumnType("datetime");

                entity.Property(e => e.Krytycznosc).HasMaxLength(1);

                entity.Property(e => e.MiejscePracy)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Nazwa)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Opis)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.OsX).HasColumnType("decimal(18, 0)");

                entity.Property(e => e.OsY).HasColumnType("decimal(18, 0)");

                entity.Property(e => e.OsZ).HasColumnType("decimal(18, 0)");

                entity.Property(e => e.Rodzaj)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Status).HasMaxLength(50);

                entity.Property(e => e.StawkaMiesieczna).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.TrybPracy)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.WartoscMaszyny).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<MozliweStatusyOferty>(entity =>
            {
                entity.Property(e => e.Status)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<MozliwyDn>(entity =>
            {
                entity.HasKey(e => e.Dn);

                entity.ToTable("MozliwyDN");

                entity.Property(e => e.Dn)
                    .HasColumnName("DN")
                    .ValueGeneratedNever();
            });

            modelBuilder.Entity<MozliwyOrderType>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                entity.Property(e => e.OrderType)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<MożliwaGrupaProcesu>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<NlogAllErrors>(entity =>
            {
                entity.ToTable("NLogAllErrors", "log");

                entity.Property(e => e.Application)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Callsite).IsUnicode(false);

                entity.Property(e => e.Exception).IsUnicode(false);

                entity.Property(e => e.Ip)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Level)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Logged).HasColumnType("datetime");

                entity.Property(e => e.Message).IsUnicode(false);

                entity.Property(e => e.User)
                    .HasMaxLength(500)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<NlogAsp>(entity =>
            {
                entity.ToTable("NLogAsp", "log");

                entity.Property(e => e.Application)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Ip)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Level)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Logged).HasColumnType("datetime");

                entity.Property(e => e.Message).IsUnicode(false);

                entity.Property(e => e.StatusCode)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Url)
                    .HasMaxLength(5000)
                    .IsUnicode(false);

                entity.Property(e => e.User)
                    .HasMaxLength(500)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<NlogOwn>(entity =>
            {
                entity.ToTable("NLogOwn", "log");

                entity.Property(e => e.Application)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Callsite).IsUnicode(false);

                entity.Property(e => e.Ip)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Level)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Logged).HasColumnType("datetime");

                entity.Property(e => e.Message).IsUnicode(false);

                entity.Property(e => e.User)
                    .HasMaxLength(500)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Offer>(entity =>
            {
                entity.Property(e => e.Name)
                   .IsRequired()
                   .HasMaxLength(50);

                entity.Property(e => e.OfferDate).HasColumnType("datetime");

                entity.Property(e => e.OrderDate).HasColumnType("datetime");

                entity.Property(e => e.OrderType)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.PlannedEnd).HasColumnType("datetime");

                entity.Property(e => e.ProjectsId).HasMaxLength(50);

                entity.Property(e => e.Status).HasMaxLength(50);

                entity.HasOne(d => d.Clients)
                    .WithMany(p => p.Offer)
                    .HasForeignKey(d => d.ClientsId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Offer__ClientsId__740F363E");

                entity.HasOne(d => d.OfferrerNavigation)
                    .WithMany(p => p.Offer)
                    .HasForeignKey(d => d.Offerrer)
                    .HasConstraintName("FK__Offer__Offerrer__3C69FB99");
            });

            modelBuilder.Entity<OfferLineProcess>(entity =>
            {
                entity.Property(e => e.ProcessId)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.OfferLine)
                    .WithMany(p => p.OfferLineProcess)
                    .HasForeignKey(d => d.OfferLineId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OfferLine__Offer__34E8D562");

                entity.HasOne(d => d.Process)
                    .WithMany(p => p.OfferLineProcess)
                    .HasForeignKey(d => d.ProcessId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OfferLine__Proce__30242045");
            });

            modelBuilder.Entity<OfferLines>(entity =>
            {
                entity.Property(e => e.Medium).HasMaxLength(150);

                entity.Property(e => e.PriceInOfferDay).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Sale).HasMaxLength(50);

                entity.Property(e => e.SalesPrice).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.W).HasMaxLength(50);

                entity.HasOne(d => d.Offer)
                    .WithMany(p => p.OfferLines)
                    .HasForeignKey(d => d.OfferId)
                    .HasConstraintName("FK__OfferLine__Offer__33008CF0");

                entity.HasOne(d => d.Product)
                    .WithMany(p => p.OfferLines)
                    .HasForeignKey(d => d.ProductId)
                    .HasConstraintName("FK__OfferLine__Produ__33F4B129");
            });

            modelBuilder.Entity<OfferProcess>(entity =>
            {
                entity.Property(e => e.ProcessId)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Offer)
                    .WithMany(p => p.OfferProcess)
                    .HasForeignKey(d => d.OfferId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OfferProc__Offer__38B96646");

                entity.HasOne(d => d.Process)
                    .WithMany(p => p.OfferProcess)
                    .HasForeignKey(d => d.ProcessId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OfferProc__Proce__39AD8A7F");
            });

            modelBuilder.Entity<Pracownik>(entity =>
            {
                entity.Property(e => e.Email).HasMaxLength(50);

                entity.Property(e => e.Login)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(70)
                    .IsUnicode(false);

                entity.Property(e => e.Rola).HasDefaultValueSql("((1))");

                entity.Property(e => e.Salt).HasMaxLength(20);

                entity.Property(e => e.StawkaGodzinowa).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.StawkaMiesieczna).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<PracownikCzasStep>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CzasStart).HasColumnType("datetime");

                entity.Property(e => e.CzasStop).HasColumnType("datetime");

                entity.Property(e => e.CzescId)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.MaszynyId)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.OfferLinesId).HasColumnName("OfferLinesID");

                entity.Property(e => e.ProcessId)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Czesc)
                    .WithMany(p => p.PracownikCzasStep)
                    .HasForeignKey(d => d.CzescId)
                    .HasConstraintName("FK_PracownikCzasStep_PracownikCzasStep2");

                entity.HasOne(d => d.Maszyny)
                    .WithMany(p => p.PracownikCzasStep)
                    .HasForeignKey(d => d.MaszynyId)
                    .HasConstraintName("FK_PracownikCzasStep_Maszyny");

                entity.HasOne(d => d.OfferLines)
                    .WithMany(p => p.PracownikCzasStep)
                    .HasForeignKey(d => d.OfferLinesId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PracownikCzasStep_OfferLines");

                entity.HasOne(d => d.Pracownik)
                    .WithMany(p => p.PracownikCzasStep)
                    .HasForeignKey(d => d.PracownikId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PracownikCzasStep_Pracownik");

                entity.HasOne(d => d.Process)
                    .WithMany(p => p.PracownikCzasStep)
                    .HasForeignKey(d => d.ProcessId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PracownikCzasStep_Process");
            });

            modelBuilder.Entity<PracownikProcess>(entity =>
            {
                entity.Property(e => e.ProcessId)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Pracownik)
                    .WithMany(p => p.PracownikProcess)
                    .HasForeignKey(d => d.PracownikId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PracownikProcess_Pracownik");
            });

            modelBuilder.Entity<Process>(entity =>
            {
                entity.Property(e => e.Id).HasMaxLength(30);

                entity.Property(e => e.BusinessArea)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.KontoGłówne).HasMaxLength(50);

                entity.Property(e => e.NazwaGrupyProcesu)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.NazwaProcesu)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.TypZlecenia)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength()
                    .HasDefaultValueSql("('R')");
            });

            modelBuilder.Entity<ProcessesProcess>(entity =>
            {
                entity.Property(e => e.ProcessId).HasMaxLength(30);

                entity.Property(e => e.RelatedProcessId).HasMaxLength(30);

                entity.HasOne(d => d.Process)
                    .WithMany(p => p.ProcessesProcessProcess)
                    .HasForeignKey(d => d.ProcessId)
                    .HasConstraintName("FK_ProcessesProcess");

                entity.HasOne(d => d.RelatedProcess)
                    .WithMany(p => p.ProcessesProcessRelatedProcess)
                    .HasForeignKey(d => d.RelatedProcessId)
                    .HasConstraintName("FK_ProcessesRelatedProcess");
            });
            modelBuilder.Entity<VProdExe>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VProdExe");

                entity.Property(e => e.Dn).HasColumnName("DN");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasMaxLength(81);

                entity.Property(e => e.IdentyfikatorZamowienia)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Klient)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.NazwaProcesu)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.NumerKlienta)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.OfferLineId).HasColumnName("OfferLineID");

                entity.Property(e => e.PlannedEnd).HasColumnType("datetime");

                entity.Property(e => e.ProcessId)
                    .IsRequired()
                    .HasColumnName("processId")
                    .HasMaxLength(30);

                entity.Property(e => e.TypProcesu)
                    .IsRequired()
                    .HasColumnName("typProcesu")
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.TypWyrobu)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Wersja)
                    .HasColumnName("wersja")
                    .HasMaxLength(5);

                entity.Property(e => e.ZakonczenieData).HasColumnType("datetime");
            });

            modelBuilder.Entity<ProduktCzesci>(entity =>
            {
                entity.Property(e => e.CzesciId)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.HasOne(d => d.Czesci)
                    .WithMany(p => p.ProduktCzesci)
                    .HasForeignKey(d => d.CzesciId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("ProduktCzesci_Czesci_FK");

                entity.HasOne(d => d.Produkt)
                    .WithMany(p => p.ProduktCzesci)
                    .HasForeignKey(d => d.ProduktId)
                    .HasConstraintName("ProduktCzesci_Produkty_FK");
            });

            modelBuilder.Entity<Produkty>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Ansi)
                    .IsRequired()
                    .HasColumnName("ANSI")
                    .HasMaxLength(5);

                entity.Property(e => e.Cena).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Dn).HasColumnName("DN");

                entity.Property(e => e.NumerRysNorma)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Pn).HasColumnName("PN");

                entity.Property(e => e.ProductName)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.TypWyrobuId)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Uszczelnienie)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Waluta).HasMaxLength(5);

                entity.Property(e => e.Wersja)
                    .IsRequired()
                    .HasMaxLength(5);
            });

            modelBuilder.Entity<ProduktyRysunkiInfo>(entity =>
            {
                entity.HasIndex(e => e.ProduktId);

                entity.HasOne(d => d.Produkt)
                    .WithMany(p => p.ProduktyRysunkiInfo)
                    .HasForeignKey(d => d.ProduktId);

                entity.HasIndex(e => e.ProduktyRysunkiId);

                entity.HasOne(d => d.ProduktyRysunki);
            });

            modelBuilder.Entity<ProduktyRysunki>(entity =>
            {

            });
            modelBuilder.Entity<CzesciRysunkiInfo>(entity =>
            {
                entity.HasIndex(e => e.CzescId);

                entity.HasOne(d => d.Czesc)
                    .WithMany(p => p.CzesciRysunkiInfo)
                    .HasForeignKey(d => d.CzescId);

                entity.HasIndex(e => e.CzesciRysunkiId);

                entity.HasOne(d => d.CzesciRysunki);
            });

            modelBuilder.Entity<CzesciRysunki>(entity =>
            {

            });

            modelBuilder.Entity<Projects>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Client).HasMaxLength(5);

                entity.Property(e => e.ClientGroup).HasMaxLength(50);

                entity.Property(e => e.DateOfferd).HasMaxLength(50);

                entity.Property(e => e.DateTd)
                    .HasColumnName("DateTD")
                    .HasMaxLength(20);

                entity.Property(e => e.Description).HasMaxLength(255);

                entity.Property(e => e.Funel).HasMaxLength(40);

                entity.Property(e => e.FunelStep).HasMaxLength(255);

                entity.Property(e => e.Id)
                    .IsRequired()
                    .HasColumnName("ID")
                    .HasMaxLength(50);

                entity.Property(e => e.Location).HasMaxLength(10);

                entity.Property(e => e.Nomination).HasMaxLength(8);

                entity.Property(e => e.Phase).HasMaxLength(10);

                entity.Property(e => e.ProductNrClient).HasMaxLength(100);

                entity.Property(e => e.ProductNrInt).HasMaxLength(20);

                entity.Property(e => e.ProductSubType).HasMaxLength(50);

                entity.Property(e => e.ProductType).HasMaxLength(50);

                entity.Property(e => e.QafNr).HasMaxLength(255);

                entity.Property(e => e.RodzajProjektu).HasMaxLength(10);

                entity.Property(e => e.Status).HasMaxLength(20);

                entity.Property(e => e.To).HasMaxLength(25);

                entity.Property(e => e.Version).HasMaxLength(10);
            });

            modelBuilder.Entity<ReasonCodes>(entity =>
            {
                entity.Property(e => e.Opis)
                    .HasMaxLength(1000)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<StepOfferWykonanie>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.ClosedOn).HasColumnType("datetime");

                entity.Property(e => e.OfferLineId).HasColumnName("OfferLineID");

                entity.Property(e => e.ProcessId)
                    .IsRequired()
                    .HasColumnName("ProcessID")
                    .HasMaxLength(30);

                entity.Property(e => e.ReasonCodeId).HasColumnName("ReasonCodeID");

                entity.Property(e => e.StartedOn).HasColumnType("datetime");

                entity.HasOne(d => d.ReasonCode)
                    .WithMany(p => p.StepOfferWykonanie)
                    .HasForeignKey(d => d.ReasonCodeId)
                    .HasConstraintName("FK_StepOfferWykonanie_ReasonCodes");
            });

            modelBuilder.Entity<Steps>(entity =>
            {
                entity.Property(e => e.ProcessesId).HasMaxLength(30);

                entity.Property(e => e.StepId).HasMaxLength(61);

                entity.Property(e => e.StepName)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.Processes)
                    .WithMany(p => p.Steps)
                    .HasForeignKey(d => d.ProcessesId)
                    .HasConstraintName("FK_PROCESS_STEP_ID");
            });

            modelBuilder.Entity<StepsMachines>(entity =>
            {
                entity.Property(e => e.MachineId)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.HasOne(d => d.Machine)
                    .WithMany(p => p.StepsMachines)
                    .HasForeignKey(d => d.MachineId)
                    .HasConstraintName("FK__StepsMach__Machi__2A6B46EF");

                entity.HasOne(d => d.Step)
                    .WithMany(p => p.StepsMachines)
                    .HasForeignKey(d => d.StepId)
                    .HasConstraintName("FK__StepsMach__StepI__451F3D2B");
            });

            modelBuilder.Entity<Towary>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.CenaSprzedazy).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CenaZakupu).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Nazwa)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.WalutaSprzedazy)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.WalutaZakupu)
                    .HasMaxLength(15)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TypWyrobu>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.IdgrupyWyrobu)
                    .IsRequired()
                    .HasColumnName("IDGrupyWyrobu")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.TypKonstrukcji)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.TypKuli)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('pływajaca')");

                entity.Property(e => e.TypPrzelotu)
                    .HasMaxLength(30)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TypWyrobuIdDn>(entity =>
            {
                entity.HasKey(e => e.TypWyrobuId);

                entity.Property(e => e.TypWyrobuId)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Dn).HasColumnName("DN");

                entity.Property(e => e.TempMax).HasDefaultValueSql("((120))");

                entity.Property(e => e.TempMin).HasDefaultValueSql("((-60))");

                entity.Property(e => e.Waga).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.WagaJednostka)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.WymiaryDlmm).HasColumnName("WymiaryDLmm");
            });

            modelBuilder.Entity<VActivityHistory>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vActivityHistory");

                entity.Property(e => e.Client)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.CzasStart).HasColumnType("datetime");

                entity.Property(e => e.CzasStop).HasColumnType("datetime");

                entity.Property(e => e.PartId)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.PartName)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.PracownikName)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.ProcessId)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.ProcessName)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.WyrobId)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<VOtifReport>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vOtifReport");

                entity.Property(e => e.ClosedOn).HasColumnType("datetime");

                entity.Property(e => e.NazwaGrupyProcesu)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.NazwaProcesu)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.PlannedEndOffer)
                    .HasColumnName("plannedEndOffer")
                    .HasColumnType("datetime");

                entity.Property(e => e.ProcessId)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.StepShouldEndBeforeDays).HasColumnName("stepShouldEndBeforeDays");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}