INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('abandonment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('absence');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('account');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('assets');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('acquisition ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('action(s)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('activities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('activities/events');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('analyses');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('adjustments');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('adjustments/deductions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('benefits');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('responsibilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('metrics');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('advances');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('baselines');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('goals');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('agreements/contracts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('alerts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('alignment principles');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('alliance ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('allocations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('system');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('deductions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('applicant data');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('applicant information');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('applicant record');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('approaches');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('approval limits');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('approval responsibilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('AR policies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('AR reports');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('architectural exceptions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('architecture conformance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('architecture governance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('architecture principles');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('asset ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resources');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('audit ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('audits');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('authentication mechanisms');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('authorization');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('availability');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('available skills');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('B strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('back plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('back procedures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('background information');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('balances');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('bank ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('bargaining process');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('baseline forecasts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('baseline metrics');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('benchmark');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('benefit');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('best practices');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('billing data');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('bills of material');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('board');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('boarding program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('brand');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('budget');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('building');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('bundling opportunities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Business ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('buy decision');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('buy solution');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('candidate');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('capabilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('capacities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('capital program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('card accounts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('card requests');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cases');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cash');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cause analysis');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cause(s)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('center accounting');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('certification');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('champion(s)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('change');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('channel');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('chargeback invoices');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('claim');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('claims');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('collect data');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('committee');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('communication ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('community relations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('compensation plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('competencies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('competition');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('competitive analysis');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('competitors');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('compliance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('component criteria');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('component maintenance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('component portfolio');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('component reuse');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('components');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('concepts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('consensus forecast');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('constrained plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('constraints');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('construction permissions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('construction resources');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('construction strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('contacts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('content strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('contingency plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('continuity');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('contract manufacturers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('contract terms');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('contracts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('control');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('copyright needs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('core competencies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('corporate incentives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cost drivers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cost effectiveness');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cost improvement');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cost management');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('costs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('credit');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('credit card');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('credit cards');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('credit limits');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('credit policies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('credit reviews');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('critical activities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cultural changes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cultural issues');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('currencies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('currency conversion');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('currency transactions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('business');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('processes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('customer');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('customers and accounts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('website');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('customs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('costing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('cycle time');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('damage cause');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('data');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('deal options');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('default accounts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('accounts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Deliver Analytics');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('delivery');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('demand ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('forecasts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('demographics');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('demotion process');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('deployment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('depreciation expense');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('design activities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('design specifications');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('design team');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('destination');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('detailed schedule');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('measures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('guidelines');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('lifecycle');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('partners');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('development ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('direction');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('directors');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('discovery research');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('dispatch plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('dispute cases');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('distribute payments');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('distribution requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('diversity plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('divesture options');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('documents');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('doskonalenie');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('drawings');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('duty');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('earnings information');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('ecological concerns');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('economic trends');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('EFTs)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('EHS performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('EHS policy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('EHS program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('elective reviews');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('electronic commerce');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('emerging regulations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('employee');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('engagement rules');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('engagement surveys');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('enterprise');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('enterprise architecture');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('enterprise quality');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('enterprise risk');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('environmental readiness');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('EQMS performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('equipment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('escalation mechanisms');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('establish contracts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('ethical issues');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('ethics');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('ethics policies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('evaluate feasibility');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('evaluate success');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('events');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('exception governance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('exceptions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('exchange risk');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('exchange trades');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('roadmap');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('controls');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('models');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('exit strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('expatriates');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('expense policies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('expense reimbursements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('experience');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('experience qualifications');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('experience requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('experience strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('experts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('exports and imports');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('exposure risk');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('external environment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('External Relationships');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('external reviews');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('external services');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('facilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('failures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('feasible alternatives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('feedback');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('financial forecasts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('financial health');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('financial performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('financial reporting');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Financial Resources');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('financial review');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('financial statements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('financial systems');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('fixed costs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('flow forecasts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('force');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('forecast');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('forecast accuracy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('forecasting approach');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('foreign taxes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('framework');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('fraudulent claims');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('fulfillment process');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('fulfillment schedule');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('fulfillment transactions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('function');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('function risk');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('functional processes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('functional requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('funding models');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('funding options');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('funds/consolidation');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('future state');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('gain/loss');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('gap analysis');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('general accounting');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('goods inventory');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('goods management');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('governance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('government bodies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('government relations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('groups');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('hazards');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('hedge currency');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('hedges');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('HR');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Human Capital');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('ideas');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('implementation ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('improvement ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('incentive plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('incentives plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('incoming feedback');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('indicators');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('indicators (metrics)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('induction program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('industry ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('influencing factors');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('information');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('infrastructure');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('inquiries');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('inspection documents');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('installation testing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('insurance coverage');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('integration');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('intelligence analysis');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('intercompany transactions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('intermediary relationships');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('internal approvals');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('internal audits');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('internal capabilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('internal controls');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('internal environment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('internal operations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('internal parties');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('internal reviews');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('international rates');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('into system');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('introduction/launch');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('inventory accounting');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('investment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('issue');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('issuer exposure');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('IT');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('job descriptions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('job requisitions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('job schedule');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('journal entries');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('journey maps');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('key account');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('key initiatives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('key processes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('KM approaches');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('KM capabilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('KM initiatives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('KM methodologies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('KM strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('KM) capability');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('knowledge');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('knowledge repository');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('labor policies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('labor relations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('launch review');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('law programs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('layout constraints');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('leadership programs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('ledger');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('legal aspects');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('legal services');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('lender relations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('level agreement');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('level agreements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('level measures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('level plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('level risks');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('licenses');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('life cycle');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('lifecycle planning');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('lifetime value');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('line schedule');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('liquidity');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('load plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('load plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('lobby activities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('logistics network');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('logistics strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('lot use');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('loyalty program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('maintenance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('offer');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('manage hypotheses');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('manage meetings');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('manage personas');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('manage pricing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management accounting');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management activities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management adjustments');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management approaches');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management consolidation');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management constraints');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management framework');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management goals');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management governance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management measures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management mechanisms');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management methodologies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management models');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management partnerships');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management process');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management processes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management reports');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management roles');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management strategies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management system');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('management training');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('managing relationships');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('manual checks');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('manufacturing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('manufacturing goals');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('market');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('marketing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('master data');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('master files');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('master lists');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('material classification');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('material flow');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('material inventory');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('material receipts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('material specifications');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('materials');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('materials plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('materials policies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('materials strategies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('measurement methods');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('mechanisms');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('media relations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('meet demand');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('members');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('merger options');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('methods');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('mission');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('mission statement');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('mitigate');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('mitigation measures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('model');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('model governance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('monitoring frequency');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('motivation programs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('needs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('net profit');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('netting transactions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('network-wide');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('new assets');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('new branding');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('new organization');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('new products');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('new roles');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('new technologies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('next steps');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('non-conformance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('notification outcome');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('numbering system');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('objectives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('objectives/targets');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('obtain funding');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('offering modifications');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('offers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('offers accordingly');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('online systems');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('operating procedures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('operating units');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('operational availability');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('operational capabilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('operational status');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('operations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('opportunities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('opportunity pipeline');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('optimization');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('option');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('options');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('order fulfillment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('order information');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('organization');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('organizational characteristics');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('organizational design');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('organizational goals');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('organizational units');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('other hours');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('other initiatives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('outbound product');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('outbound transportation');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('outcomes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('outside counsel');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('outsourcing needs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('outsourcing policies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('packaging strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('party details');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('paths');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('pay');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('payable (AP)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('payables taxes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('payment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('payments');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('payroll');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('payroll ');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('payroll taxes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('penetration testing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('people objectives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance assessments');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance indicators');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance management');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance measures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance metrics');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance objectives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance targets');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('performance trends');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('personnel accounts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('physical positions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Physical Products');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('pipeline');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('plan attainment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('planning constraints');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('planning/strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('policies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('policies and offerings');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('policy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Poprawa Procesu');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('portfolio');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('portfolio adjustments');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('portfolio governance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('portfolio strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('positioning');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('potential customers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('potential impact');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('potential partners');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('PR) strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('press releases');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('prevention program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('price changes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('pricing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('pricing analysis');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('pricing performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('pricing plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('pricing programs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('pricing strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('pricing targets');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('priorities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('priority');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('procedure');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('procedure workflow');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('procedures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process assessment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process collections');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process control');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process efficiency');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process eliminations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process exceptions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process framework');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process frameworks');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process ownership');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('process performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('procurement plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product copy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product costing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product delivered');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product images');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product mix');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product profitability');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product repair');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product revenue');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product servicing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product upgrades');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('product’ offering');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('production performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('production process');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('production runs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('production schedule');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('productive assets');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('products');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('products and services');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('products/services');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('profitability analysis');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('program execution');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('programs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('project');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('project accounting');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('project approval');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('project management approach');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('project outcomes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('project plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('project plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Project resources');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('project scope');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('projects');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('promotional activities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('promotions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('property concerns');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('prototypes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('provide support');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('purchase orders');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('purchasing requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality activities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality characteristics');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality controls');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality partnerships');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality samples');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality specifications');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality targets');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quality testing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('quotes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('rate risk');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('rate trades');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('rate transactions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recall');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recall effectiveness');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recall performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recall strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recall termination');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('receivable (AR)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('receivable entries');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('record reason');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recovery action');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recovery claims');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recovery workout');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recruitment channels');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recruitment program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('recruitment vendors');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('redesign workshops');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('referral programs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('regulatory agencies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('regulatory audits');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('regulatory compliance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('regulatory issues');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('regulatory requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('re-hire');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('reject decision');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('related communications');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('related entries');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('relations program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('relationships');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('release compliance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('release deployment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('release impact');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('release outcome');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('release risk');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('release standards');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('reliability problems');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('re-manufacturing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('remedial actions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('remediate risk');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('remediation efforts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('remediation plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('remediation requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('repair expenses');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('repairs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('replenishment planning');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('report performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('reporting');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('reporting process');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('reporting processes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('reports');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('repositories');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('require change');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('required capabilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('required competencies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('required resources');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('requisition dates');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('requisitions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('research and assessments');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('research initiatives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('research projects');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resilience strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Resiliency');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resolution');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resolve threats');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resource administration');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resource allocation');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resource availability');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resource demand');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resource deployment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resource plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resource planning');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resource requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('resources strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('response program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('responsible executives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('responsible party');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('restitution');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('restrictions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('restructuring opportunities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('result(s)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('retention');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('retirement');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('retires');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('return');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('returned parts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('returned products');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('returns');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('revenue accounting');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('reversals');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('revise forecast');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('reward approaches');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('reward plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('rewards');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('risk');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('risk analysis');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('risk and opportunities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('risk governance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('risk ownership');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('risk policy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('risk tolerance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('risk tolerances');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('risks');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('risks resiliency');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('rollout issues');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('rollout plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('routings');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('safety (EHS)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('safety impacts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sale');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sale trends and patterns');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sales activities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sales analysis');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sales budgets');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sales calls');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sales forecast');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sales orders');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sales partners');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sales plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sales strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sales team');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('salvage activities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sample significance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sampling plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('satisfaction');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('satisfy inquiries');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('schedule');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('scheduling estimates');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('scope');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('scorecard(s)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('scoring requirement');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('security');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('security requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('segments');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('selection tools');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('separation');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sequence');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service catalog');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service concepts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service contacts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service delivery');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service demand');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service expectations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service experience');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service framework');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service levels');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service management');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service order');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service policy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service portfolio');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service project');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service representatives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('service strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('services');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('services catalog');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('services delivered');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('services interdependencies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('services strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('services/solutions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('shareholders');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sheet risk');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('shortfalls therein');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sick leave');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('simulate plant');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sites');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('skills taxonomy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('SLA compliance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution approach');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution architecture');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution architectures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution communications');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution design');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution development');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution implementation');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution lifecycle');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution operations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution packaging');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution remediation');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution rollout');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('solution validation');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('source');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sourcing relationships');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sourcing strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('specification data');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('specifications');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('spend profile');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('staff productivity');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('staffing requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('stakeholder requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('stakeholders');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('standards');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('stewardship responsibilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategic alignment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategic initiatives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategic intelligence');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategic options');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategic priorities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategic priority');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategic relationships');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategic vision');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('strategy models');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('structure');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('subsidiaries');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('succession plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sunset" plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('supplier capacity');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('supplier information');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('supplier recovery');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('suppliers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('supply');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('supply capabilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('supply chain methodologies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('supply constraints');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support capabilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support compliance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support learning');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support model');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support needs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support planning');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support portfolio');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support procedures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support providers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support resources');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support structure');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('support systems');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('sustainability strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('system (EQMS)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('systems');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('systems HRIS');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('systems model');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('target audience');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('target segments');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('targets');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('targets/contracts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('tax compliance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('tax data');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('tax forms');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('tax plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('tax returns');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('tax strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('taxes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technical assessment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technical requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technical training');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technologies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technology');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Technology (IT)');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technology aspects');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technology capabilities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technology concepts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technology innovation');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technology innovations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('technology solutions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('templates');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('term vision');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('test equipment');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('testing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('testing procedures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('tests');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('tests and interviews');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('the change');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('the customer');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('the market');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('the objectives');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('the organization');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('the partnerships');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('the project');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('the relationships');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('threat assessments');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('threat impact');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('time optimization');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('time worked');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('to change');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('to customer');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('to proceed');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('to promise');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('to requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('tools');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('traceability');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('traceability data');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('trade');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('trade preferences');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('trade services');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('trademarks');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('train employees');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('training');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('training effectiveness');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('training materials');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('training plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('training program');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('training programs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('training schedule');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('transactions');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('transfers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('transformation needs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('transformation plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('transformation roadmap');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('transformation strategy');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('transportation fleet');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('treasury');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('treasury operations');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('treasury policies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('treasury procedures');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('trial balance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('unconstrained plan');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('unit');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('unit strategies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('unit/organization');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('update plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('update systems');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('updates');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('usage audits');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('user authorization');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('user directory');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('user requests');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('user support');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('utilization');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('validate suppliers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('value contribution');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('value criteria');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('value drivers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('value portfolio');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('value proposition');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('variable costs');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('variance analysis');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('vendor performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('viable concepts');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('vision');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('volumes');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('warehouse transfers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('warehousing');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('warranty');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('warranty claim');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('warranty claims');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('warranty issues');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('warranty offering');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('warranty performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('warranty policies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('warranty waste');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('win plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('with agencies');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('with authorities');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('with customers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('with suppliers');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('work performance');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('work plans');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('work requirements');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('work safety');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('workforce scheduling');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Wyrób niezgodny');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('z serwisu');
INSERT INTO[dbo].[ProcessSubject]([Nazwa])VALUES('Zarzadzanie auditem');
